#!/usr/bin/env python3
"""Generate Rev11 from Rev10 by adding ENBW positioning and practical uncertainty guidance.

Rev11 changes no theorem, proof, resource bound, or worked-example number.
It narrows novelty positioning by acknowledging the exact single-mark
mathematical identity with conventional one-sided equivalent noise bandwidth.
"""
from pathlib import Path

main_src = Path('event_resource_theorem_rev10.tex')
main_out = Path('event_resource_theorem_rev11.tex')
sec_src = Path('section_practical_grounding_rev9.tex')
sec_out = Path('section_practical_grounding_rev11.tex')

assert main_src.exists() and sec_src.exists()
s = sec_src.read_text(encoding='utf-8')

old = r'''\begin{equation}
B_{\rm FI}=\frac12\int f(t)^2dt.
\label{eq:singleMarkBFI}
\end{equation}
Thus capture efficiency controls the absolute Fisher-information scale through $G(0)=\eta$, while the DC-normalized equivalent bandwidth depends only on the \emph{shape} of the conditional timing law.'''
new = r'''\begin{equation}
B_{\rm FI}=\frac12\int f(t)^2dt.
\label{eq:singleMarkBFI}
\end{equation}
\paragraph{Relation to conventional equivalent noise bandwidth.}
For a single unresolved mark, Eq.~\eqref{eq:singleMarkBFI} is mathematically identical to the conventional one-sided equivalent noise bandwidth (ENBW) of a unit-DC-gain low-pass transfer function \cite{MotchenbacherConnelly1993}:
\begin{equation}
B_{\rm ENBW}=\int_0^\infty
\frac{|H(2\pi f)|^2}{|H(0)|^2}\,df.
\label{eq:ENBWidentity}
\end{equation}
Because a conditional delay characteristic function satisfies $H(0)=1$, the scalar single-mark identity is exactly $B_{\rm FI}=B_{\rm ENBW}$. This mathematical coincidence is useful rather than a novelty claim. The interpretation and generalization here are different: $H$ is generated by stochastic event-registration latency; the retained-mark transfer $G(\omega)=\int |H_m(\omega)|^2\kappa(dm)$ is not, in general, the ENBW of the mark-discarded scalar timing law; its spectral area equals the collision resource $\mathfrak R_2$; and it obeys the Fisher-ordering, microscopic-hazard, and inverse resource-cost results derived above. Conventional circuit ENBW therefore supplies the familiar scalar integral, but not the marked event-channel Fisher/resource theory.

Thus capture efficiency controls the absolute Fisher-information scale through $G(0)=\eta$, while the DC-normalized equivalent bandwidth depends only on the \emph{shape} of the conditional timing law.'''
assert s.count(old) == 1
s = s.replace(old, new, 1)

old = r'''\end{equation}
This is directly computable from a saved histogram.

Finite binning is itself a temporal coarse graining.'''
new = r'''\end{equation}
This is directly computable from a saved histogram. A practical finite-sample uncertainty estimate can be obtained by a multinomial plug-in bootstrap: draw replicate count vectors from $\operatorname{Multinomial}(N,\widehat{\boldsymbol p})$, recompute Eq.~\eqref{eq:histUnbiased}, and use the empirical replicate distribution for uncertainty intervals. Such intervals describe counting uncertainty of the \emph{binned} estimator only; they do not include systematic uncertainty from instrument jitter, background subtraction, digitization, or deconvolution.

Finite binning is itself a temporal coarse graining.'''
assert s.count(old) == 1
s = s.replace(old, new, 1)

assert 'B_{\\rm FI}=B_{\\rm ENBW}' in s
assert 'multinomial plug-in bootstrap' in s
sec_out.write_text(s, encoding='utf-8')

m = main_src.read_text(encoding='utf-8')
anchor = r'\input{section_practical_grounding_rev9}'
assert m.count(anchor) == 1
m = m.replace(anchor, r'\input{section_practical_grounding_rev11}', 1)
assert m.count(r'\input{section_practical_grounding_rev11}') == 1
main_out.write_text(m, encoding='utf-8')
print(f'generated {sec_out} and {main_out}')
